# @package _global_

model:
  ssm_init:
    C_init: lecun_normal
    dt_min: 0.004
    dt_max: 0.1
    conj_sym: false
    clip_eigs: false
  ssm:
    discretization: async
    d_model: 96
    d_ssm: 128
    ssm_block_size: 8
    num_stages: 2
    num_layers_per_stage: 3
    dropout: 0.23
    classification_mode: pool
    prenorm: true
    batchnorm: false
    bn_momentum: 0.95
    pooling_stride: 8
    pooling_mode: avgpool
    state_expansion_factor: 1