# @package _global_
defaults:
  - /model: shd/tiny

task:
  name: shd-classification

training:
  num_epochs: 5
  per_device_batch_size: 16
  per_device_eval_batch_size: 16
  num_workers: 4
  time_jitter: 1
  spatial_jitter: 0.55
  noise: 35
  max_drop_chunk: 0.02
  drop_event: 0.1
  time_skew: 1.2
  cut_mix: 0.3
  pad_unit: 8192
  validate_on_test: false

optimizer:
  ssm_base_lr: 5e-5
  lr_factor: 10
  warmup_epochs: 1
  ssm_weight_decay: 0.0
  weight_decay: 0.01
  schedule: cosine
  accumulation_steps: 1